# Generated by Django 5.1.1 on 2024-10-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemeTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("default_top_text", models.CharField(max_length=100)),
                ("default_bottom_text", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Meme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("top_text", models.CharField(max_length=100)),
                ("bottom_text", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memes.memetemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="memes.meme"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("meme", "user")},
            },
        ),
    ]
