# Generated by Django 5.1.1 on 2024-10-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="image_url",
        ),
    ]
